# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [ ]:
import numpy as np
# Код оголошення векторів не можна змінювати
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

In [ ]:
res = a + b
res

array([[1.5, 3. , 5. , 7. , 9. ]])

In [ ]:
res = a - b
res

array([[0.5, 1. , 1. , 1. , 1. ]])

In [ ]:
# Пояснення: формуються вектори до спільної форми (5×5), і додаються відповідні елементи. Це називається broadcasting.
res = a + b.T
res

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [ ]:
res = a @ b.T
res

array([[40.5]])

In [ ]:
# Пояснення: помилка, тому що кількість рядків матриці а дорвінює 5, а кількість рядів матриці b дорівнює 1.  множення  підтримується лише за умови рівних показників.
res = a @ b
res

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [ ]:
# Пояснення: Покомпонентне множення
res = a * b
res

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

In [ ]:
# Пояснення: Елементне ділення a[i] / b[i].
res = a / b
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

In [ ]:
# Пояснення: Broadcasting, як у додаванні.
res = a / b.T
res

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
0.5 & 0\\
0 & 3\\
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
0.5 & 0\\
0 & 3
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
0.5 \cdot 2 + 0 \cdot 1\\
0 \cdot 2 + 3 \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
1\\
3
\end{array}\right)
$$

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 =
\left(\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right)
\\
M_2x =
\left(\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
-2\\
-1
\end{array}\right)
$$

#### 2.3 Перенеси вектор $x$, задавши відповідну матрицю і помноживши на неї,  на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 =
\left(\begin{array}{cc}
1 & 0 & -3\\
0 & 1 & 1\\
0 & 0 & 1
\end{array}\right)
\\
\\
M_3x =
\left(\begin{array}{cc}
1 & 0 & -3\\
0 & 1 & 1\\
0 & 0 & 1
\end{array}\right)
\left(\begin{array}{cc}
2 \\
1 \\
1
\end{array}\right)
 =
 \left(\begin{array}{cc}
-1 \\
2 \\
1
\end{array}\right)=
 \left(\begin{array}{cc}
-1 \\
2
\end{array}\right)
$$

#### 2.4 Змісти(shear) вектор $x$ на 60° по вісі $OY$.


$$
M_4 =
\left(\begin{array}{cc}
1 & tan(60°)\\
0 & 1
\end{array}\right)
\\
M_4x =
\left(\begin{array}{cc}
1 & tan(60°)\\
0 & 1
\end{array}\right)
\left(\begin{array}{cc}
2 \\
1
\end{array}\right) =
\left(\begin{array}{cc}
2 + \sqrt{3}\\
1
\end{array}\right)
$$

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 =
\left(\begin{array}{cc}
cos(30°) & -sin(30°)\\
sin(30°) & cos(30°)
\end{array}\right)
\\
M_5x =
\left(\begin{array}{cc}
cos(30°) & -sin(30°)\\
sin(30°) & cos(30°)
\end{array}\right)
\left(\begin{array}{cc}
2 \\
1
\end{array}\right) =
\left(\begin{array}{cc}
\sqrt{3} -0.5 \\
1 + \frac{\sqrt{3}}{2}
\end{array}\right)
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 =

$$

$$
M_6 =
\left(\begin{array}{cc}
-\frac{\sqrt{3}}{4} && -3 \\
- \frac{1}{4} && -3\sqrt{3}
\end{array}\right)
\\
M_6x =
\left(\begin{array}{cc}
-\frac{\sqrt{3}}{4} && -3 \\
- \frac{1}{4} && -3\sqrt{3}
\end{array}\right)
\left(\begin{array}{cc}
2 \\
1
\end{array}\right) =
\left(\begin{array}{cc}
-3 & -\frac{\sqrt{3}}{2} \\
-\frac{1}{2} & -3\sqrt{3}
\end{array}\right)  
$$

# Завдання 2 (Альтернативне)

In [11]:
# на локалхост код працює і зміни відбуваються, в цьому середовищі малюнок за урл не отримується.
import cv2
import urllib
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow as cv_imshow

# Функція для завантаження зображення за URL
def read_image_by_url(url):
    req = urllib.request.urlopen(url)  # Відкриваємо URL
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)  # Перетворюємо в масив байтів
    img = cv2.imdecode(arr, -1)  # Декодуємо зображення
    return img

# Приклад URL (замість цього вставте своє посилання на зображення)
url = 'https://en.wikipedia.org/wiki/Main_Page#/media/File:Leucocrinum_montanum_-_Cecelia_Alexander_04.jpg'

# Завантажуємо зображення за URL
img = read_image_by_url(url)

# Переводимо зображення в RGB для відображення з matplotlib
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


# Переводимо зображення в RGB для відображення з matplotlib
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Матриця масштабування (M1) - зменшуємо по осі OX в 2 рази, збільшуємо по осі OY в 3 рази
M1 = np.array([[0.5, 0, 0], [0, 3, 0], [0, 0, 1]], dtype=np.float32)

# Матриця відображення (M2) - відображаємо відносно початку координат
M2 = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]], dtype=np.float32)

# Матриця зміщення (shear) по осі OY на 60°
shear_angle = 60  # градуси
shear_radians = np.deg2rad(shear_angle)
M4 = np.array([[1, np.tan(shear_radians), 0], [0, 1, 0], [0, 0, 1]], dtype=np.float32)

# Матриця повороту (M5) на 30°
rotation_angle = 30  # градуси
rotation_radians = np.deg2rad(rotation_angle)
M5 = np.array([[np.cos(rotation_radians), -np.sin(rotation_radians), 0],
               [np.sin(rotation_radians), np.cos(rotation_radians), 0],
               [0, 0, 1]], dtype=np.float32)

# Перевіримо поетапно кожне перетворення окремо, щоб знайти причину
# 1. Масштабування
img_scaled = cv2.warpPerspective(img, M1, (img.shape[1], img.shape[0]))
# Відображаємо результат після масштабування
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Оригінальне зображення")
plt.axis("off")

plt.subplot(1, 2, 2)
img_scaled_rgb = cv2.cvtColor(img_scaled, cv2.COLOR_BGR2RGB)
plt.imshow(img_scaled_rgb)
plt.title("Після масштабування")
plt.axis("off")
plt.show()

# 2. Відображення
img_reflected = cv2.warpPerspective(img, M2, (img.shape[1], img.shape[0]))
# Відображаємо результат після відображення
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Оригінальне зображення")
plt.axis("off")

plt.subplot(1, 2, 2)
img_reflected_rgb = cv2.cvtColor(img_reflected, cv2.COLOR_BGR2RGB)
plt.imshow(img_reflected_rgb)
plt.title("Після відображення")
plt.axis("off")
plt.show()

# 3. Зміщення
img_sheared = cv2.warpPerspective(img, M4, (img.shape[1], img.shape[0]))
# Відображаємо результат після зміщення
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Оригінальне зображення")
plt.axis("off")

plt.subplot(1, 2, 2)
img_sheared_rgb = cv2.cvtColor(img_sheared, cv2.COLOR_BGR2RGB)
plt.imshow(img_sheared_rgb)
plt.title("Після зміщення")
plt.axis("off")
plt.show()

# 4. Поворот
img_rotated = cv2.warpPerspective(img, M5, (img.shape[1], img.shape[0]))
# Відображаємо результат після повороту
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Оригінальне зображення")
plt.axis("off")

plt.subplot(1, 2, 2)
img_rotated_rgb = cv2.cvtColor(img_rotated, cv2.COLOR_BGR2RGB)
plt.imshow(img_rotated_rgb)
plt.title("Після повороту")
plt.axis("off")
plt.show()

# 5. Об'єднуємо всі матриці
M6 = M5 @ M4 @ M2 @ M1  # Перемножуємо матриці
output_img = cv2.warpPerspective(img, M6, (int(img.shape[1] * 1.5), int(img.shape[0] * 1.5)))  # Розширення розмірів

# Відображаємо фінальне перетворене зображення
plt.figure(figsize=(10, 10))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Оригінальне зображення")
plt.axis("off")

plt.subplot(1, 2, 2)
output_img_rgb = cv2.cvtColor(output_img, cv2.COLOR_BGR2RGB)
plt.imshow(output_img_rgb)
plt.title("Перетворене зображення")
plt.axis("off")

plt.show()



error: OpenCV(4.11.0) /io/opencv/modules/imgproc/src/color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [10]:
cv_imshow(img)

AttributeError: 'NoneType' object has no attribute 'clip'